### ISSUE TITLE
Multiple radarr/sonarr instances

### ISSUE THREAD

**Issue by raphaelgrau** [ManiMatter/decluttarr#121]
Just wondering if it would be easy to add the possibility to handle multiple radarr instances. This is something often used to manage a radarr hd and a radarr 4k. Thanks!

**Comment by ManiMatter** [comment]
Simple answer: Just run two instances of it, as you do with radarr/sonarr. 
I do not plan to manage 2 radarr instances out of the same decluttarr, particulalrly not since radarr team said they contemplate adding support for multiple qualities within the same radarr in the future. So for now, just use 2x decluttarr.
