### ISSUE TITLE
Feature request: ignore paused

### ISSUE THREAD

**Issue by swxxii** [ManiMatter/decluttarr#148]
I use this with remove slow enabled but I have found this has the unwanted side effect of also removing torrents which I have manually paused. I will often do this for example, when I want to give one torrent priority I will pause all others. It would be great to add an option to prevent removing torrents which have been manually paused.

**Comment by ManiMatter** [comment]
Which job removes the paused ones currently for you? 
Are you using qbit (and have connected it with decluttarr)?

The reason I'm asking is because in theory already now paused downloads should be ignored, since slow-check only looks at "downloading" ones.

https://github.com/ManiMatter/decluttarr/blob/ae4cc993efd6827780b407d819b5107d43b84064/src/jobs/remove_slow.py#L57

Can you provide screenshots 
1) How it looks before you pause
2) When you pause

then pls switch the logs to debug-mode and paste them to a pastebin and provide the link.
Would like to see how that queue of yours looks like (ie. what the queue download status is - whether "downloading" or "paused"). If it says downloading but in qbit the status is paused, then thats a mapping issue on sonarr/radarr side.

**Comment by swxxii** [comment]
It happens with both the Radarr and Sonarr jobs. I am using Transmission perhaps that is the issue?

**Comment by ManiMatter** [comment]
Which specific jobs? Just the "slow" check or also others?

Please post the queue response - Im 99% convinced that your status says "downloading" instead of "paused", which means the mapping in Sonarr would not be correct.

**Comment by ManiMatter** [comment]
Ping?

**Comment by ManiMatter** [comment]
Will close on the weekend if no response

**Comment by ManiMatter** [comment]
Closed since no response
