### ISSUE TITLE
Feature Request: Remove downloads with "Last Seen Complete: Never"

### ISSUE THREAD

**Issue by codersaur** [ManiMatter/decluttarr#167]
I am finding that the downloads I have to manually delete in qBittorrent are the ones that have "Last Seen Complete: Never". It would be great if this tool can identify those, ideally applying a threshold time period for last seen complete.

**Comment by ManiMatter** [comment]
Screenshot pls?

**Comment by codersaur** [comment]
![image](https://github.com/user-attachments/assets/ad103957-f1ce-463f-92e6-412cd7700328)

Looking into the qBittorrent API, it should be possible to identify these downloads from the /api/v2/torrents/info endpoint where the torrent has "seen_complete" =  -1.

**Comment by ManiMatter** [comment]
Are those downloads that have  availability for files < 1? (check on the info endpoint pls).

If yes, then that's the same issue I think as discussed here:
https://github.com/ManiMatter/decluttarr/issues/142

I got a bit frustrated that I spent time on it and the person who had requested it just disappeared.
The story is a bit more nuanced with the availability. Just shooting down the torrents that have <100% availability, is the crude way, since it may also delete torrents where all relevant files have downloaded and just a "Readme" file, for example, is not downloading (few kb out of 5gb torrent).

What we started over there is to say: Can we exclude files that we're not interest in, and then check the availability for the rest?

If you are committed to invest time with me on this and help me with testing, logs, etc on a rapid pace, happy to reopen the other ticket. 

wdyt?

**Comment by codersaur** [comment]
Yes, looking at the data for my torrents, those with seen_complete=-1 also seem to have availability<1.

Tbh, I would be happy with a crude option to remove torrents with seen_complete=-1 or availability<1, so long as PERMITTED_ATTEMPTS is also applied. Perhaps a threshold could be set for the availability value?

That said, I am more than happy to help test the more-advanced solution.

**Comment by ManiMatter** [comment]
Closing this. Can you pls read the other thread and download the mentioned image/apply the qbit settings and post your answers to my questions in the other thread? Will then continue eorking on it
