### ISSUE TITLE
Docker Desktop (Windows) Docker Run

### ISSUE THREAD

**Issue by phoenixevolved** [ManiMatter/decluttarr#192]
I made this work on a basic level for docker desktop users. 

docker run --name=Decluttarr --env=RADARR_URL='http://IPGOESHERE:PORT' --env=RADARR_KEY='APIKEYGOESHERE' --env=SONARR_URL='http://IPGOESHERE:PORT' --env=SONARR_KEY='APIKEYGOESHERE' --env=QBITTORRENT_URL='http://IPGOESHERE:PORT' --env=QBITTORRENT_USERNAME='USERNAME' --env=QBITTORRENT_PASSWORD='PASSWORD' ghcr.io/manimatter/decluttarr:latest

im new to this and a windows person so I had to make this thing work :) 
idk if you can clean this up for me and add it to the instructions but I would appreciate it!

**Comment by phoenixevolved** [comment]
also, for me Localhost or 127.0.0.1 wouldn't work, needed the actual LAN IP of the Server

**Comment by ManiMatter** [comment]
Not planning to add myself since not a windows user and would not be sble to tell if right or wrong. Any windows user will hopefully find your pointers above when searching the closed issues when dealing with a similar question.

if you have a clean how-to description, happy to accept a PR to get it added to the readme
