### ISSUE TITLE
[feature request] autoremove torrent seeding for x time or seed ration > x

### ISSUE THREAD

**Issue by spupuz** [ManiMatter/decluttarr#44]
feature request autoremove torrent seeding for x time or seed ration > x

like this tools does:

https://github.com/jerrymakesjelly/autoremove-torrents

**Comment by ManiMatter** [comment]
I would not see this as as a feature for decluttarr for two reasons:
1) there seems to be a working alternative
2) focus of decluttarr is enabling the *arr apps to get data rather than getting stuck; the requested feature aims at what hsppens afterwards, ie seeding post download completion

thus not planned unless there is a strong reason for it to be added
