### ISSUE TITLE
[Feature request] Remove by setting post import category

### ISSUE THREAD

**Issue by HomebrewDotNET** [ManiMatter/decluttarr#51]
I'm currently using qBit_Manage to manage my torrent in qBitTorrent. Mainly for private tracker requirements.
I'm using post import categories in Radarr/Sonarr so qBit_Manage knows which torrents it's allowed to delete.

I'd like an option to set the post import category instead of deleting. (Like the option you can now select in Radarr/Sonarr)

**Comment by ManiMatter** [comment]
I think the purpose of decluttarr is different. It should find ‚stuck‘ downloads and replace them with working ones.

how to deal with successful downloads (ie whether to keep them to meet seed targets, etc) is not the focus; for that you probs want to keep relying on other tools

**Comment by undaunt** [comment]
I'd like to revisit this, considering the use case with failed imports due to not being an upgrade.

For example, I do not want qbit-manage to scan my download category for things which have no hardlinks, only my post-import category, otherwise there could be a race condition of completed torrents being scanned and tagged as no hardlink before their import is complete (eg: on season packs).

When I am manually cleaning up torrents which are not upgrades (eg: a 720p and then a 1080p file in quick succession get grabbed via Autobrr for something) I put them in the post-import category via the Sonarr UI so then qbit will subsequently tag them as no hardlink, share group them, and eventually remove them after minimum seeding requirements are met.

Right now I need to manually move torrents decluttarr removes from the import queue into the post-import category or qbit-manage will not clean them up.

**Comment by undaunt** [comment]
See https://github.com/ManiMatter/decluttarr/pull/234

@HomebrewDotNET fyi
