### ISSUE TITLE
A humble feature request!

### ISSUE THREAD

**Issue by MikeFalcor** [ManiMatter/decluttarr#7]
First off, I **really** appreciate your help in trying to rid us all of the issue surrounding qBit and the ARRs doing absolutely nothing with stagnant torrents. THANK YOU!

### My request:
I would like to split apart the scheduling for the various modes of failure. Ideally, I would like to differentiate between stalled DLs and those that never download metadata. My opinion is that those that do not download metadata are hard failures and should be treated differently from stalls. As such, the removal and reattempt should be much quicker.

My config allows the script to run every 10 minutes and removes torrents after 72 attempts. That's 720 minutes or 12 hours. I figured that was a nice period of time for SOMETHING to happen with a given torrent. BUT, if it fails to even download metadata, I'd like to get rid of it after an hour or 6 attempts. "If it doesn't get the metadata after an hour, it probably never will."

What are your thoughts on this?

**Comment by ManiMatter** [comment]
Hi Mike

thanks very much for reaching out and the kind words.

I see where you are coming from. Personally, I would not differentiate the number of permitted attempts between stalled & no metadata. 

I agree that no metadata can be seen as hard fail whereas stalled might recover.

With a setting of 10min cycles and 3 permitted attempts, the metadata items get out of the way quickly, and I think we are both happy with these.

The reason I also want to kill the stalled ones after 30min is because most of the torrents have alternatives where the entire download duration is less than 30. So if a download doesn‘t manage to show a sign of life, I‘d rather try another one.

I would not give it 12h (I am probably not as patient as you 😁). Particularly, if we gave stalled ones a 12h grace period, and somewhere in that period it once shows downloading with 0.01Kb/s for 20min, and then goes stalled again, the clock would be reset snd we‘d never actually would get rid of it.

Where I have a torrent that I want to show mercy  I exclude it using the „Don‘t kill if stalled“ tag; if it‘s still there after 2-3 days, I can always still remove the tag.

wdyt? :)

**Comment by MikeFalcor** [comment]
I do see your point and I think I **will** change my settings...for now. I have also, however, seen torrents come back to life after a long period of time (which, I think, is probably due to the original seeder coming back on to pick up the slack of the hit-n-runners).

**Comment by ManiMatter** [comment]
Cool, closed therefore
