### ISSUE TITLE
[Feature Request] Optionally track "strikes" via a text file

### ISSUE THREAD

**Issue by alexx-ftw** [ManiMatter/decluttarr#79]
First, thanks for building and sharing this tool.

Right now, every time the script is restarted, the "strikes" are reset back to 0.

I would be nice being able to log this "strikes" onto a text file so that even if the computer or the script are restarted, the history of the torrents is not lost

**Comment by ManiMatter** [comment]
Thanks @alexx-ftw 

The is designed to keep running and after n strikes remove the torrent, and waiting t minutes between the strikes.

If n and t are sensibly configured (I use 3 strikes in 10min intervals), even if the computer was restarted, latest 40min later the torrent would be killed. 

Thus not seeing the big advantage here. If you want to resume where the tracking was before restarting, could you use hibernate instead of shutdown?

**Comment by ManiMatter** [comment]
Closed as no feedback / not planned
